<a href="https://colab.research.google.com/github/Psousace/Fundos_Imobiliarios/blob/main/FIIS_ORIGINAL_ESTUDOS_PAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Analizando Fundos Imobiliarios
##Referencias
>Codigo Inicial:edmilson.torres@gmail.com

>Adições ao codigo: Stack

>Video Stack: https://www.youtube.com/watch?v=hsivPUfjjTU&t=822s

##1. Bibliotecas

In [ ]:
import pandas as pd
import requests
import numpy as np

##2. Definindo cabeçalho da requisição

In [ ]:
headers = {
    'authority': 'www.fundsexplorer.com.br',
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'pt-BR,pt;q=0.5',
    'referer': 'https://www.fundsexplorer.com.br/ranking',
    'sec-ch-ua': '"Not/A)Brand";v="99", "Brave";v="115", "Chromium";v="115"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'sec-gpc': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36',
    'x-funds-nonce': '61495f60b533cc40ad822e054998a3190ea9bca0d94791a1da',
}

response = requests.get('https://www.fundsexplorer.com.br/wp-json/funds/v1/get-ranking', headers=headers)

In [ ]:
df = pd.read_json(response.json())
df

,post_id,ticker,dividendo,yeld,media_yield_3m,soma_yield_3m,media_yield_6m,soma_yield_6m,media_yield_12m,soma_yield_12m,...,setor_slug,valor,liquidezmediadiaria,patrimonio,pvp,p_vpa,post_title,v_fisica,v_financeira,ativos
0,495,AAZQ11,0.1200,1.28,1.2200,3.66,1.3300,7.98,1.5900,9.54,...,indefinido,9.31,782828,2.306468e+08,1.0052,0.969792,AAZQ11,NaN,NaN,
1,238,ABCP11,0.5000,0.70,0.7067,2.12,0.7317,4.39,0.7408,8.89,...,shoppings,69.46,55114.03,4.325528e+08,0.7562,0.756480,ABCP11,NaN,NaN,1
2,177,AFHI11,1.0500,1.07,1.1000,3.30,1.1250,6.75,1.0900,13.08,...,papeis,96.91,1427109.5,2.897112e+08,1.0100,1.022042,AFHI11,NaN,NaN,0
3,553,AGRX11,0.1200,1.08,1.3967,4.19,1.4983,8.99,1.4345,15.78,...,outros,10.65,332380,0.000000e+00,0.0000,NaN,AGRX11,NaN,NaN,0
4,56,AIEC11,0.7600,1.06,1.1233,3.37,1.1833,7.10,1.0942,13.13,...,lajes-corporativas,70.24,639515.25,4.569453e+08,0.7417,0.684888,AIEC11,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,174,XTED11,11.1600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,lajes-corporativas,8.82,17641.88,6.737820e+07,0.6771,0.314755,XTED11,NaN,NaN,1
386,175,YUFI11,0.2980,0.37,0.2833,0.85,0.1817,1.09,0.0991,1.09,...,fundo-de-desenvolvimento,94.99,184,5.009801e+07,0.9341,NaN,YUFI11,NaN,NaN,28
387,537,YUFI11B,0.6331,0.00,0.0000,0.00,0.0000,0.00,0.0000,0.00,...,indefinido,NaN,None,NaN,NaN,NaN,YUFI11B,NaN,NaN,0
388,1866,ZAVI11,1.1200,0.88,0.8900,2.67,0.8733,5.24,0.8756,7.88,...,indefinido,127.82,227010.9,1.586591e+08,0.9453,NaN,ZAVI11,NaN,NaN,9
389,295,ZIFI11,3.3050,0.00,0.0000,0.00,0.0000,0.00,0.0000,0.00,...,fundo-de-desenvolvimento,860.00,26259.56,5.725747e+07,0.7132,NaN,ZIFI11,NaN,NaN,0

In [ ]:
df.to_csv("fiis.csv")

In [ ]:
df.to_excel('fiis.xlsx')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 39 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   post_id                  390 non-null    int64
 1   ticker                   390 non-null    object
 2   dividendo                390 non-null    float64
 3   yeld                     372 non-null    float64
 4   media_yield_3m           372 non-null    float64
 5   soma_yield_3m            372 non-null    float64
 6   media_yield_6m           372 non-null    float64
 7   soma_yield_6m            372 non-null    float64
 8   media_yield_12m          372 non-null    float64
 9   soma_yield_12m           372 non-null    float64
 10  variacao_cotacao_mes     372 non-null    float64
 11  rentabilidade            286 non-null    float64
 12  rentabilidade_mes        372 non-null    float64
 13  cotacao_fechamento       299 non-null    float64
 14  soma_yield_ano_corrente  371 non-null    float64
 15  ano                      374 non-null    float64
 16  vpa_yield                297 non-null    float64
 17  vpa                      297 non-null    float64
 18  vpa_change               297 non-null    float64
 19  pl                       297 non-null    float64
 20  vpa_rent                 297 non-null    float64
 21  vpa_rent_m               297 non-null    float64
 22  yield_vpa_3m_sum         278 non-null    float64
 23  yield_vpa_3m             278 non-null    float64
 24  yield_vpa_6m_sum         222 non-null    float64
 25  yield_vpa_6m             222 non-null    float64
 26  yield_vpa_12m_sum        28 non-null     float64
 27  yield_vpa_12m            28 non-null     float64
 28  setor                    390 non-null    object
 29  setor_slug               390 non-null    object
 30  valor                    389 non-null    float64
 31  liquidezmediadiaria      389 non-null    object
 32  patrimonio               389 non-null    float64
 33  pvp                      389 non-null    float64
 34  p_vpa                    290 non-null    float64
 35  post_title               390 non-null    object
 36  v_fisica                 0 non-null      float64
 37  v_financeira             0 non-null      float64
 38  ativos                   390 non-null    object
dtypes: float64(32), int64(1), object(6)
memory usage: 119.0+ KB

In [ ]:
df.describe(include='all')

,post_id,ticker,dividendo,yeld,media_yield_3m,soma_yield_3m,media_yield_6m,soma_yield_6m,media_yield_12m,soma_yield_12m,...,setor_slug,valor,liquidezmediadiaria,patrimonio,pvp,p_vpa,post_title,v_fisica,v_financeira,ativos
count,390.000000,390,390.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,...,390,389.000000,389,3.890000e+02,389.000000,290.000000,390,0.0,0.0,390
unique,NaN,390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17,NaN,354,NaN,NaN,NaN,390,NaN,NaN,35
top,NaN,AAZQ11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,papeis,NaN,,NaN,NaN,NaN,AAZQ11,NaN,NaN,0
freq,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80,NaN,36,NaN,NaN,NaN,1,NaN,NaN,168
mean,401.246154,NaN,13.234856,0.967253,1.060491,2.795532,1.214836,6.248101,1.137424,11.149395,...,NaN,616.321568,NaN,4.476098e+08,7.330534,0.872425,NaN,NaN,NaN,NaN
std,480.191394,NaN,140.441915,3.374590,3.556209,5.503199,3.847424,13.037878,3.477975,16.080219,...,NaN,6218.764220,NaN,7.943799e+08,103.637985,0.343720,NaN,NaN,NaN,NaN
min,47.000000,NaN,0.000700,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,0.000000,NaN,-1.454803e+07,0.000000,0.060486,NaN,NaN,NaN,NaN
25%,172.250000,NaN,0.452725,0.487500,0.494175,1.422500,0.584025,3.277500,0.619350,6.547500,...,NaN,37.960000,NaN,6.264046e+07,0.629000,0.749824,NaN,NaN,NaN,NaN
50%,292.500000,NaN,0.775000,0.800000,0.861650,2.580000,0.895000,5.330000,0.900800,10.455000,...,NaN,87.830000,NaN,1.716086e+08,0.912800,0.940681,NaN,NaN,NaN,NaN
75%,405.500000,NaN,1.200000,1.020000,1.114150,3.300000,1.149550,6.790000,1.097475,12.712500,...,NaN,103.980000,NaN,4.325528e+08,0.988300,1.005310,NaN,NaN,NaN,NaN
max,2614.000000,NaN,2002.089700,62.870000,62.870000,82.610000,62.870000,142.240000,62.870000,189.830000,...,NaN,94794.810000,NaN,7.984130e+09,1961.666700,4.808909,NaN,NaN,NaN,NaN

In [ ]:
df['setor'].unique()

array(['Indefinido', 'Shoppings', 'Papéis', 'Outros',
       'Lajes Corporativas', 'Fundo de Fundos', 'Misto',
       'Imóveis Residenciais', 'Imóveis Industriais e Logísticos',
       'Imóveis Comerciais - Outros', 'Agências de Bancos',
       'Fundo de Desenvolvimento', 'Varejo', 'Fiagro', 'Educacional',
       'Hospitalar', 'Hotéis'], dtype=object)

In [ ]:
df.columns

Index(['post_id', 'ticker', 'dividendo', 'yeld', 'media_yield_3m',
       'soma_yield_3m', 'media_yield_6m', 'soma_yield_6m', 'media_yield_12m',
       'soma_yield_12m', 'variacao_cotacao_mes', 'rentabilidade',
       'rentabilidade_mes', 'cotacao_fechamento', 'soma_yield_ano_corrente',
       'ano', 'vpa_yield', 'vpa', 'vpa_change', 'pl', 'vpa_rent', 'vpa_rent_m',
       'yield_vpa_3m_sum', 'yield_vpa_3m', 'yield_vpa_6m_sum', 'yield_vpa_6m',
       'yield_vpa_12m_sum', 'yield_vpa_12m', 'setor', 'setor_slug', 'valor',
       'liquidezmediadiaria', 'patrimonio', 'pvp', 'p_vpa', 'post_title',
       'v_fisica', 'v_financeira', 'ativos'],
      dtype='object')

## 2. Limpeza e Formatação de Dado

In [ ]:
df.isna().sum()

post_id                      0
ticker                       0
dividendo                    0
yeld                        18
media_yield_3m              18
soma_yield_3m               18
media_yield_6m              18
soma_yield_6m               18
media_yield_12m             18
soma_yield_12m              18
variacao_cotacao_mes        18
rentabilidade              104
rentabilidade_mes           18
cotacao_fechamento          91
soma_yield_ano_corrente     19
ano                         16
vpa_yield                   93
vpa                         93
vpa_change                  93
pl                          93
vpa_rent                    93
vpa_rent_m                  93
yield_vpa_3m_sum           112
yield_vpa_3m               112
yield_vpa_6m_sum           168
yield_vpa_6m               168
yield_vpa_12m_sum          362
yield_vpa_12m              362
setor                        0
setor_slug                   0
valor                        1
liquidezmediadiaria          1
patrimonio                   1
pvp                          1
p_vpa                      100
post_title                   0
v_fisica                   390
v_financeira               390
ativos                       0
dtype: int64

## Dados categóricos

In [ ]:
categorical_columns = ['ticker','setor']

In [ ]:
idx = df[df['setor'].isna()].index
df.drop(idx, inplace=True)

In [ ]:
df[categorical_columns].isna().sum()

ticker    0
setor     0
dtype: int64

In [ ]:
df[categorical_columns] = df[categorical_columns].astype('category')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 39 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   post_id                  390 non-null    int64
 1   ticker                   390 non-null    category
 2   dividendo                390 non-null    float64
 3   yeld                     372 non-null    float64
 4   media_yield_3m           372 non-null    float64
 5   soma_yield_3m            372 non-null    float64
 6   media_yield_6m           372 non-null    float64
 7   soma_yield_6m            372 non-null    float64
 8   media_yield_12m          372 non-null    float64
 9   soma_yield_12m           372 non-null    float64
 10  variacao_cotacao_mes     372 non-null    float64
 11  rentabilidade            286 non-null    float64
 12  rentabilidade_mes        372 non-null    float64
 13  cotacao_fechamento       299 non-null    float64
 14  soma_yield_ano_corrente  371 non-null    float64
 15  ano                      374 non-null    float64
 16  vpa_yield                297 non-null    float64
 17  vpa                      297 non-null    float64
 18  vpa_change               297 non-null    float64
 19  pl                       297 non-null    float64
 20  vpa_rent                 297 non-null    float64
 21  vpa_rent_m               297 non-null    float64
 22  yield_vpa_3m_sum         278 non-null    float64
 23  yield_vpa_3m             278 non-null    float64
 24  yield_vpa_6m_sum         222 non-null    float64
 25  yield_vpa_6m             222 non-null    float64
 26  yield_vpa_12m_sum        28 non-null     float64
 27  yield_vpa_12m            28 non-null     float64
 28  setor                    390 non-null    category
 29  setor_slug               390 non-null    object
 30  valor                    389 non-null    float64
 31  liquidezmediadiaria      389 non-null    object
 32  patrimonio               389 non-null    float64
 33  pvp                      389 non-null    float64
 34  p_vpa                    290 non-null    float64
 35  post_title               390 non-null    object
 36  v_fisica                 0 non-null      float64
 37  v_financeira             0 non-null      float64
 38  ativos                   390 non-null    object
dtypes: category(2), float64(32), int64(1), object(4)
memory usage: 125.8+ KB

In [ ]:
df.isna().sum()

post_id                      0
ticker                       0
dividendo                    0
yeld                        18
media_yield_3m              18
soma_yield_3m               18
media_yield_6m              18
soma_yield_6m               18
media_yield_12m             18
soma_yield_12m              18
variacao_cotacao_mes        18
rentabilidade              104
rentabilidade_mes           18
cotacao_fechamento          91
soma_yield_ano_corrente     19
ano                         16
vpa_yield                   93
vpa                         93
vpa_change                  93
pl                          93
vpa_rent                    93
vpa_rent_m                  93
yield_vpa_3m_sum           112
yield_vpa_3m               112
yield_vpa_6m_sum           168
yield_vpa_6m               168
yield_vpa_12m_sum          362
yield_vpa_12m              362
setor                        0
setor_slug                   0
valor                        1
liquidezmediadiaria          1
patrimonio                   1
pvp                          1
p_vpa                      100
post_title                   0
v_fisica                   390
v_financeira               390
ativos                       0
dtype: int64

## Dados Numéricos

In [ ]:
col_floats = list(df.iloc[:,2:-1].columns)

In [ ]:
## Dados nulos
df[col_floats] = df[col_floats].fillna(value=0)

In [ ]:
df[col_floats]

,dividendo,yeld,media_yield_3m,soma_yield_3m,media_yield_6m,soma_yield_6m,media_yield_12m,soma_yield_12m,variacao_cotacao_mes,rentabilidade,...,setor,setor_slug,valor,liquidezmediadiaria,patrimonio,pvp,p_vpa,post_title,v_fisica,v_financeira
0,0.1200,1.28,1.2200,3.66,1.3300,7.98,1.5900,9.54,-3.3986,5.4391,...,Indefinido,indefinido,9.31,782828,2.306468e+08,1.0052,0.969792,AAZQ11,0.0,0.0
1,0.5000,0.70,0.7067,2.12,0.7317,4.39,0.7408,8.89,0.4751,2.2676,...,Shoppings,shoppings,69.46,55114.03,4.325528e+08,0.7562,0.756480,ABCP11,0.0,0.0
2,1.0500,1.07,1.1000,3.30,1.1250,6.75,1.0900,13.08,-0.8911,9.1779,...,Papéis,papeis,96.91,1427109.5,2.897112e+08,1.0100,1.022042,AFHI11,0.0,0.0
3,0.1200,1.08,1.3967,4.19,1.4983,8.99,1.4345,15.78,-2.4540,20.5708,...,Outros,outros,10.65,332380,0.000000e+00,0.0000,0.000000,AGRX11,0.0,0.0
4,0.7600,1.06,1.1233,3.37,1.1833,7.10,1.0942,13.13,1.0162,10.8876,...,Lajes Corporativas,lajes-corporativas,70.24,639515.25,4.569453e+08,0.7417,0.684888,AIEC11,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,11.1600,0.00,0.0000,0.00,0.0000,0.00,0.0000,0.00,0.0000,0.0000,...,Lajes Corporativas,lajes-corporativas,8.82,17641.88,6.737820e+07,0.6771,0.314755,XTED11,0.0,0.0
386,0.2980,0.37,0.2833,0.85,0.1817,1.09,0.0991,1.09,-19.9740,-23.2657,...,Fundo de Desenvolvimento,fundo-de-desenvolvimento,94.99,184,5.009801e+07,0.9341,0.000000,YUFI11,0.0,0.0
387,0.6331,0.00,0.0000,0.00,0.0000,0.00,0.0000,0.00,0.0000,0.0000,...,Indefinido,indefinido,0.00,0,0.000000e+00,0.0000,0.000000,YUFI11B,0.0,0.0
388,1.1200,0.88,0.8900,2.67,0.8733,5.24,0.8756,7.88,0.6158,4.1051,...,Indefinido,indefinido,127.82,227010.9,1.586591e+08,0.9453,0.000000,ZAVI11,0.0,0.0
389,3.3050,0.00,0.0000,0.00,0.0000,0.00,0.0000,0.00,0.0000,0.0000,...,Fundo de Desenvolvimento,fundo-de-desenvolvimento,860.00,26259.56,5.725747e+07,0.7132,0.000000,ZIFI11,0.0,0.0

In [ ]:
df[col_floats].head()

,dividendo,yeld,media_yield_3m,soma_yield_3m,media_yield_6m,soma_yield_6m,media_yield_12m,soma_yield_12m,variacao_cotacao_mes,rentabilidade,...,setor,setor_slug,valor,liquidezmediadiaria,patrimonio,pvp,p_vpa,post_title,v_fisica,v_financeira
0,0.12,1.28,1.2200,3.66,1.3300,7.98,1.5900,9.54,-3.3986,5.4391,...,Indefinido,indefinido,9.31,782828,2.306468e+08,1.0052,0.969792,AAZQ11,0.0,0.0
1,0.50,0.70,0.7067,2.12,0.7317,4.39,0.7408,8.89,0.4751,2.2676,...,Shoppings,shoppings,69.46,55114.03,4.325528e+08,0.7562,0.756480,ABCP11,0.0,0.0
2,1.05,1.07,1.1000,3.30,1.1250,6.75,1.0900,13.08,-0.8911,9.1779,...,Papéis,papeis,96.91,1427109.5,2.897112e+08,1.0100,1.022042,AFHI11,0.0,0.0
3,0.12,1.08,1.3967,4.19,1.4983,8.99,1.4345,15.78,-2.4540,20.5708,...,Outros,outros,10.65,332380,0.000000e+00,0.0000,0.000000,AGRX11,0.0,0.0
4,0.76,1.06,1.1233,3.37,1.1833,7.10,1.0942,13.13,1.0162,10.8876,...,Lajes Corporativas,lajes-corporativas,70.24,639515.25,4.569453e+08,0.7417,0.684888,AIEC11,0.0,0.0

In [ ]:
df[col_floats] = df[col_floats].applymap(lambda x: str(x).replace('R$', '').replace('.0','').replace('.','').replace('%','').replace(',','.'))

##Analisando Média por setor

In [ ]:
df['setor'].unique()

In [ ]:
df.columns

In [ ]:
indicadores = ['ticker',
              'setor_slug',
              'media_yield_12m',
              'soma_yield_12m',
              'rentabilidade_mes',
              'pvp',
              'vpa_change',
              'vpa_rent',
              'vpa_rent',
              'liquidezmediadiaria']

In [ ]:
df_aux = df[indicadores]
df_aux

In [ ]:
media_setor_slug = df_aux.groupby('setor_slug').agg(['mean', 'std'])

In [ ]:
media_setor_slug

In [ ]:
media_setor_slug.to_excel('Media_setor.xlsx')

In [ ]:
media_setor_slug.loc['lajes-corporativas', ('media_yield_12m', 'mean')]

# Criando uma função com uma estratégia para oportunidde de Mercado

In [ ]:
def oportunidade_media_setor_slug(df, setor_slug='shoppings', label_setor_slug='setor_slug'):
  media_setor_slug = df_aux.groupby('setor_slug').agg(['mean','std'])
  df_setor_slug = df[df[label_setor_slug].isin([setor_slug])]
  filter_ = \
          (df_setor_slug['Ativos'] >5 &\
           df_setor_slug['liquidezmediadiaria'] >0 &
           df_setor_slug['pvp'] <0 &
           df_setor_slug['media_yield_12m'] > media_setor_slug.loc[setor_slug, ('media_yield_12m', 'mean')])

In [ ]:
list(df['setor_slug'].unique())

In [ ]:
oportunidade = oportunidade_media_setor_slug(df_aux, setor_slug='imoveis-residenciais')
oportunidade.sort_values('media_yield_12m', ascending=False, inplace=True)
oportunidade